# Site settings
# title: An awesome title!
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Errin's landing page.
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: irk3n
github_username: errinlarsen

# Build settings
markdown: kramdown

# [ahawkins _config.yml](https://github.com/ahawkins/hawkins.io)
# permalink: /:year/:month/:title
# markdown: redcarpet
# redcarpet:
#   extensions: [fenced_code_blocks, autolink]
